services:
  frontend:
    image: ishnoopy/fit-check-frontend:latest
    container_name: frontend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: ishnoopy/fit-check-backend:latest
    container_name: backend
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - DB_URL=${DB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - "4000:4000"

  mongo:
    image: mongo:7.0.14
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:1.27.3-alpine
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/certs:/etc/letsencrypt:ro
      - ./nginx/certbot:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/certbot:/var/www/certbot
    entrypoint: >
      certbot certonly --webroot --webroot-path=/var/www/certbot --email ishnoopy@gmail.com --agree-tos --no-eff-email -d fit-check.ishnoopy.space

volumes:
  mongo_data:
